// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Firefox",      
  handlers: [
    {
      match: /^https?:\/\/ntusupportprod$/,
      browser: "Google Chrome"
    },
    {
      match: /^https?:\/\/youtube$/,
      browser: "Brave Browser"
    },
    {
      match: /^https?:\/\/patreon$/,
      browser: "Brave Browser"
    },
    {
      match: /^https?:\/\/sessionize$/,
      browser: "Google Chrome"
    }
  ]
}
