#example for demo
export DOTFILES=~/dotfiles
export TERM=xterm
export TERMINFO='/usr/share/terminfo/'

source ~/dotfiles/zsh/plugins/zsh-snap/znap.zsh
#if [ -z "$TMUX" ]; then
#    export TERM=xterm-256color-italic
#else
#    export TERM=tmux-256color
#fi

#Set vim keybindings
bindkey -v
export KEYTIMEOUT=1

#Remove aliases before reimporting
unalias -m '*'
source $DOTFILES/zsh/zsh-aliases

source $DOTFILES/zsh/zsh-functions

#Aliases that don't go publisc
if [[ -f "$DOTFILES/zsh/zsh-aliases-private" ]]; then
    source $DOTFILES/zsh/zsh-aliases-private
fi

source $DOTFILES/zsh/zprompt	


setopt AUTOCD EXTENDEDGLOB NOMATCH MENUCOMPLETE
setopt INTERACTIVE_COMMENTS

# history setup
setopt SHARE_HISTORY
#setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS HIST_FIND_NO_DUPS 
#INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
export SAVEHIST=100000000
export HISTFILE=~/.zsh_history
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
export HISTTIMEFORMAT="[%F %T] "

#export PROMPT_COMMAND="history -a; history -r; $PROMPT_COMMAND"

znap source marlonrichert/zsh-autocomplete
zstyle ':autocomplete:*' min-input 1  # int

znap source zsh-users/zsh-syntax-highlighting
znap source hlissner/zsh-autopair
autoload -Uz add-zsh-hook vcs_info
# Wait until this many characters have been typed, before showing completions

#set up history. 
  #pretty ls
  export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
  export CLICOLOR=1

# wordaround for non keyed server

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Azure CLI path completion
autoload bashcompinit && bashcompinit source '$HOME/lib/azure-cli/az.completion'

# VI bindings
set -o vi
export EDITOR=vim


#iTerm tab header refresh
#if [ $ITERM_SESSION_ID ]; then
#  export PROMPT_COMMAND='echo -ne "\033];${PWD##*/}\007"; ':"$PROMPT_COMMAND";
#fi


#eval "$(rbenv init -)"

#if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
#  __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
#  GIT_PROMPT_ONLY_IN_REPO=0
#  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
#fi
#FLAGS


export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
#PATH mangling
export PATH="$PATH:$DOTFILES/cht.sh"
export PATH="$HOME/.gem/ruby/2.7.0/bin:$PATH"
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export PATH="/usr/local/opt/python@3.8/bin:$PATH"
export PATH="$PATH:$HOME/bin:$HOME/Library/Python/2.7/bin"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
